_target_: bloodbank_marl.utils.evosax.strategies.open_es.OpenES
popsize: ${evosax.num_train_rollouts}
opt_name: "adam"
lrate_init: 0.08
sigma_init: 0.08
sigma_decay: 1.0
lrate_decay: 1.0
lrate_limit:
  _target_: operator.mul
  _args_:
    - ${evosax.strategy.lrate_init}
    - 0.01
sigma_limit:
  _target_: operator.mul
  _args_:
    - ${evosax.strategy.sigma_init}
    - 0.01