_target_: bloodbank_marl.utils.evosax.strategies.simple_ga.SimpleGA
popsize: ${evosax.popsize}
elite_ratio: 0.5
sigma_init: 0.08
sigma_decay: 1.0
sigma_limit:
  _target_: operator.mul
  _args_:
    - ${evosax.strategy.sigma_init}
    - 0.0001