defaults:
  - environment: simple_two_product_perishable_gymnax_test_double
  - policies/replenishment: single_agent_multi_product_mlp
  - policies/issuing: single_agent_multi_product_mlp
  - pymoo/algorithm: nsgaii
  - _self_

wandb:
  init:
    project: "simple_two_product_perishable_pymoo"
    tags:
      - "new_type_env"

hydra:
  job:
    chdir: True
  searchpath:
    - pkg://bloodbank_marl.common_config

pymoo:
  num_generations: 100
  pop_size: 2000
  n_offsprings: 150
  num_train_rollouts: 100
  #num_test_rollouts: 1000
  #evaluate_every_k_gens: 10
  seed: 10

  problem:
    min_service_level_pc: -1.0
    max_wastage_pc: 101.0
    min_exact_match_pc: -1.0
    xu: 5.0
    xl:
      _target_: operator.mul
      _args_:
        - -1.0
        - ${pymoo.problem.xu}

  termination:
    _target_: pymoo.termination.get_termination
    name: "n_gen"
    n_max_gen: ${pymoo.num_generations}
  
  #checkpoint_options:
  #  _target_: orbax.checkpoint.CheckpointManagerOptions
  #  max_to_keep: 1
  #  create: True
    
train_evaluator:
  _target_: bloodbank_marl.utils.single_agent_fit_issue_too_fitness_manager.GymnaxFitness
  env_name: ${environment.env_name}
  num_env_steps: ${environment.num_env_steps}
  num_rollouts: ${pymoo.num_train_rollouts}
  env_kwargs: ${environment.env_kwargs}
  env_params: ${environment.env_params}
  test: False
  n_devices:
  num_warmup_days: ${environment.num_warmup_days}
  gamma: ${environment.gamma}

# CUrrently not used
#evaluation:
#  seed: 1337
#  test_evaluator:
#    _target_: bloodbank_marl.utils.single_agent_fit_issue_too_fitness_manager.GymnaxFitness
#    env_name: ${environment.env_name}
#    num_env_steps: ${environment.num_env_steps}
#    num_rollouts: ${pymoo.num_test_rollouts}
#    env_kwargs: ${environment.env_kwargs}
#    env_params: ${environment.env_params}
#    test: True
#    n_devices:
#    num_warmup_days: ${environment.num_warmup_days}
#    gamma: ${environment.gamma}