# m2 exp2
python run_pretraining_replenishment_classification.py +experiment=single_product_perishable/m2/exp2/fit_nn
python run_pretraining_replenishment_classification.py +experiment=single_product_perishable/m2/exp2/fit_order_up_to_nn

# m2 exp6
python run_pretraining_replenishment_classification.py +experiment=single_product_perishable/m2/exp6/fit_nn
python run_pretraining_replenishment_classification.py +experiment=single_product_perishable/m2/exp6/fit_order_up_to_nn

# m5 exp2
python run_pretraining_replenishment_classification.py +experiment=single_product_perishable/m5/exp2/fit_nn
python run_pretraining_replenishment_classification.py +experiment=single_product_perishable/m5/exp2/fit_order_up_to_nn

# m5 exp6
python run_pretraining_replenishment_classification.py +experiment=single_product_perishable/m5/exp6/fit_nn
python run_pretraining_replenishment_classification.py +experiment=single_product_perishable/m5/exp6/fit_order_up_to_nn