defaults:
  - environment: de_moor_perishable
  - replenishment/policy: one_product_mlp
  - issuing/policy: one_product_mlp
  - _self_

wandb:
  init:
    project: "marl_ppo_jax_demoor"
plot_policies: False

training:
  num_envs: 40
  seed: 123

replenishment:
  num_envs: ${training.num_envs}
  lr: 2.5e-4
  num_steps: 50
  total_timesteps: 1e6
  update_epochs: 3
  num_minibatches: 10
  gamma: 0.9
  gae_lambda: 0.95
  clip_eps: 0.2
  ent_coef: 0.01
  vf_coef: 0.5
  max_grad_norm: 0.5
  anneal_lr: True

issuing:
  num_envs: ${training.num_envs}
  lr: 2.5e-4
  num_steps: 200
  total_timesteps: 4e6
  update_epochs: 3
  num_minibatches: 20
  gamma: 0.9
  gae_lambda: 0.95
  clip_eps: 0.2
  ent_coef: 0.01
  vf_coef: 0.5
  max_grad_norm: 0.5
  activation: "tanh"
  anneal_lr: True

evaluation:
  seed: 456
  test_evaluator:
    _target_: bloodbank_marl.utils.gymnax_fitness.GymnaxFitness
    env_name: ${environment.env_name}
    num_env_steps: ${environment.num_env_steps}
    num_rollouts: 10000
    env_kwargs: ${environment.env_kwargs}
    env_params: ${environment.env_params}
    test: True
    n_devices:
    num_warmup_days: ${environment.num_warmup_days}
    gamma: ${environment.gamma}



