_target_: bloodbank_marl.policies.common.FlaxStochasticMAPolicy
model_class:
  _target_: hydra.utils.get_class
  path: bloodbank_marl.policies.models.flax_stochastic.DiscreteActorCritic
model_kwargs:
  activation: "tanh"
policy_id: 0
env_name: ${environment.env_name}
env_kwargs: ${environment.env_kwargs}
env_params: ${environment.env_params}