defaults:
  - environment: de_moor_perishable
  - policies/replenishment: discrete_order_up_to_mlp
  - policies/issuing: discrete_mlp
  - _self_

wandb:
  init:
    project: "bloodbank_marl_neuroevolution_default"

evosax:
  num_generations: 100
  evaluate_every_k_gens: 10
  seed: 10
  
  strategy:
    _target_: evosax.OpenES
    popsize: 150
    opt_name: "adam"
    lrate_init: 0.08
    sigma_init: 0.08

  fitness_shaper:
    _target_: evosax.FitnessShaper
    maximize: True

  logging:
    _target_: evosax.utils.ESLog
    num_generations: ${evosax.num_generations}
    top_k: 5
    maximize: ${evosax.fitness_shaper.maximize}

  checkpoint_options:
    _target_: orbax.checkpoint.CheckpointManagerOptions
    max_to_keep: 1
    create: True

train_evaluator:
  _target_: bloodbank_marl.utils.gymnax_fitness.GymnaxFitness
  env_name: ${environment.env_name}
  num_env_steps: ${environment.num_env_steps}
  num_rollouts: ${environment.num_rollouts}
  env_kwargs: ${environment.env_kwargs}
  env_params: ${environment.env_params}
  test: False
  n_devices:
  num_warmup_days: ${environment.num_warmup_days}
  max_warmup_steps: ${environment.max_warmup_steps}
  gamma: ${environment.gamma}

test_evaluator:
  _target_: bloodbank_marl.utils.gymnax_fitness.GymnaxFitness
  env_name: ${environment.env_name}
  num_env_steps: ${environment.num_env_steps}
  num_rollouts: 10000
  env_kwargs: ${environment.env_kwargs}
  env_params: ${environment.env_params}
  test: True
  n_devices:
  num_warmup_days: ${environment.num_warmup_days}
  max_warmup_steps: ${environment.max_warmup_steps}
  gamma: ${environment.gamma}

policies:
  optimize:
    - 0 # replenishment
    - 1 # issuing
  policy_manager:
    _target_: bloodbank_marl.policies.policy_manager.PolicyManager



