_target_: bloodbank_marl.policies.common.FixedPolicy
policy_function:
  _target_: hydra.utils.get_method
  path: bloodbank_marl.policies.issuing.issue_exact_match
policy_params:
env_kwargs: ${environment.env_kwargs}