defaults:
  - heuristic_policy: heuristic_order_up_to
  - policies/replenishment: single_agent_single_product_order_up_to_mlp
  - policies/issuing:
  - param_search: grid
  - evosax/strategy: simple_ga
  - environment: de_moor_perishable_gymnax
  - _self_

wandb:
  init:
    project: "de_moor_pareto_frontier_plots"

hydra:
  job:
    chdir: True
  searchpath:
    - pkg://bloodbank_marl.common_config

evosax:
  num_generations: 100
  popsize: 150
  num_train_rollouts: 100
  num_test_rollouts: 1000
  evaluate_every_k_gens: 10
  seed: 10
  init_prev_best: False
  fitness_shaper:
    _target_: evosax.FitnessShaper
    maximize: True

  logging:
    _target_: evosax.utils.ESLog
    num_generations: ${evosax.num_generations}
    top_k: 5
    maximize: ${evosax.fitness_shaper.maximize}

kpi_ranges:
  wastage_pc:
    _target_: numpy.arange
    start: 0.5
    stop: 10.5
    step: 0.5
  service_level_pc:
    _target_: numpy.arange
    start: 50
    stop: 95
    step: 5

train_evaluator:
  _target_: bloodbank_marl.utils.single_agent_gymnax_fitness.GymnaxFitness
  env_name: ${environment.env_name}
  num_env_steps: ${environment.num_env_steps}
  num_rollouts: ${evosax.num_train_rollouts}
  env_kwargs: ${environment.env_kwargs}
  env_params: ${environment.env_params}
  test: False
  n_devices:
  num_warmup_days: ${environment.num_warmup_days}
  gamma: ${environment.gamma}

evaluation: 
  seed: 1337 
  test_evaluator:
    _target_: bloodbank_marl.utils.single_agent_gymnax_fitness.GymnaxFitness
    env_name: ${environment.env_name}
    num_env_steps: ${environment.num_env_steps}
    num_rollouts: ${evosax.num_test_rollouts}
    env_kwargs: ${environment.env_kwargs}
    env_params: ${environment.env_params}
    test: True
    n_devices:
    num_warmup_days: ${environment.num_warmup_days}
    gamma: ${environment.gamma}