wandb_version: 1

obs_collection:
  desc: null
  value:
    policies:
      issuing:
        _target_: bloodbank_marl.policies.issuing.heuristic.OldestCompatibleIssuingPolicy
        env_name: RSPerishableIncIssueGymnax
        env_params:
          poisson_demand_mean:
          - 4.7
          - 4.7
          - 4.9
          - 4.7
          - 5.1
          - 3.4
          - 3.6
          product_probabilities:
          - 0.07
          - 0.38
          - 0.06
          - 0.34
          - 0.02
          - 0.09
          - 0.01
          - 0.03
          age_on_arrival_distribution_probs:
          - 0.5
          - 0.2
          - 0.3
          fixed_order_cost: 225
          variable_order_costs:
          - 650
          - 650
          - 650
          - 650
          - 650
          - 650
          - 650
          - 650
          shortage_costs:
          - 3250
          - 3250
          - 3250
          - 3250
          - 3250
          - 3250
          - 3250
          - 3250
          wastage_costs:
          - 650
          - 650
          - 650
          - 650
          - 650
          - 650
          - 650
          - 650
          holding_costs:
          - 130
          - 130
          - 130
          - 130
          - 130
          - 130
          - 130
          - 130
          max_substitution_cost: 650
          initial_weekday: -1
          max_wastage_pc_target: 100.0
          min_service_level_pc_target: 0.0
          min_exact_match_pc_target: 0.0
          target_kpi_breach_penalty: 0.0
          max_steps_in_episode: 365
          gamma: 1.0
        fixed_policy_params:
          _target_: jax.numpy.array
          object:
          - - 0
            - 4
            - 2
            - -1
            - -1
            - -1
            - -1
            - -1
          - - 1
            - 0
            - 5
            - 4
            - 3
            - 2
            - -1
            - -1
          - - 2
            - 6
            - 4
            - 0
            - 3
            - 7
            - -1
            - -1
          - - 3
            - 2
            - 7
            - 6
            - 5
            - 4
            - -1
            - -1
          - - 4
            - 6
            - 2
            - 0
            - 5
            - 7
            - -1
            - -1
          - - 5
            - 4
            - 7
            - 6
            - 3
            - 2
            - -1
            - -1
          - - 6
            - 2
            - 4
            - 0
            - 7
            - 3
            - -1
            - -1
          - - 7
            - 6
            - 3
            - 2
            - 5
            - 4
            - -1
            - -1
      policy_manager:
        _target_: bloodbank_marl.policies.policy_manager.PolicyManager
      replenishment:
        _target_: bloodbank_marl.policies.replenishment.heuristic.SRepPolicyExploreMA
        env_name: RSPerishable
        env_kwargs:
          n_products: 8
          max_useful_life: 3
          lead_time: 0
          max_order_quantity: 5
          max_demand: 100
        env_params:
          poisson_demand_mean:
          - 4.7
          - 4.7
          - 4.9
          - 4.7
          - 5.1
          - 3.4
          - 3.6
          product_probabilities:
          - 0.07
          - 0.38
          - 0.06
          - 0.34
          - 0.02
          - 0.09
          - 0.01
          - 0.03
          age_on_arrival_distribution_probs:
          - 0.5
          - 0.2
          - 0.3
          fixed_order_cost: 225
          variable_order_costs:
          - 650
          - 650
          - 650
          - 650
          - 650
          - 650
          - 650
          - 650
          shortage_costs:
          - 3250
          - 3250
          - 3250
          - 3250
          - 3250
          - 3250
          - 3250
          - 3250
          wastage_costs:
          - 650
          - 650
          - 650
          - 650
          - 650
          - 650
          - 650
          - 650
          holding_costs:
          - 130
          - 130
          - 130
          - 130
          - 130
          - 130
          - 130
          - 130
          max_substitution_cost: 650
          initial_weekday: -1
          max_wastage_pc_target: 100.0
          min_service_level_pc_target: 0.0
          min_exact_match_pc_target: 0.0
          target_kpi_breach_penalty: 0.0
          max_steps_in_episode: 365
          gamma: 1.0
        epsilon: 0.05
        exploration_sampling: uniform
        params_min: 0
        params_max: 5
        fixed_policy_params:
          _target_: jax.numpy.array
          object:
          - - 1
          - - 0
          - - 2
          - - 2
          - - 0
          - - 2
          - - 0
          - - 0
    environment:
      env_name: RSPerishable
      num_env_steps: 1000000.0
      num_rollouts: 100
      env_kwargs:
        n_products: 8
        max_useful_life: 3
        lead_time: 0
        max_order_quantity: 5
        max_demand: 100
      env_params:
        poisson_demand_mean:
        - 4.7
        - 4.7
        - 4.9
        - 4.7
        - 5.1
        - 3.4
        - 3.6
        product_probabilities:
        - 0.07
        - 0.38
        - 0.06
        - 0.34
        - 0.02
        - 0.09
        - 0.01
        - 0.03
        age_on_arrival_distribution_probs:
        - 0.5
        - 0.2
        - 0.3
        fixed_order_cost: 225
        variable_order_costs:
        - 650
        - 650
        - 650
        - 650
        - 650
        - 650
        - 650
        - 650
        shortage_costs:
        - 3250
        - 3250
        - 3250
        - 3250
        - 3250
        - 3250
        - 3250
        - 3250
        wastage_costs:
        - 650
        - 650
        - 650
        - 650
        - 650
        - 650
        - 650
        - 650
        holding_costs:
        - 130
        - 130
        - 130
        - 130
        - 130
        - 130
        - 130
        - 130
        max_substitution_cost: 650
        initial_weekday: -1
        max_wastage_pc_target: 100.0
        min_service_level_pc_target: 0.0
        min_exact_match_pc_target: 0.0
        target_kpi_breach_penalty: 0.0
        max_steps_in_episode: 365
        gamma: 1.0
      num_warmup_days: 100
      gamma: 1.0
      kpis_log_eval:
      - mean_daily_reward
      - mean_total_order
      - service_level_%
      - expiries_%
      - mean_holding
      - exact_match_%
      - mean_age_at_transfusion
    seed: 12345
    num_envs: 20
    samples_per_env: 1000
policies:
  desc: null
  value:
    issuing:
      _target_: bloodbank_marl.policies.issuing.flax_nn.FlaxMultiProductIssuePolicySingleAgentEnv
      model_class:
        _target_: hydra.utils.get_class
        path: bloodbank_marl.policies.models.flax_deterministic.IssueMultiProductMLP
      model_kwargs:
        n_hidden: 64
      env_name: RSPerishableIncIssueGymnax
      env_kwargs:
        n_products: 8
        max_useful_life: 3
        lead_time: 0
        max_order_quantity: 5
        max_demand: 100
      env_params:
        poisson_demand_mean:
        - 4.7
        - 4.7
        - 4.9
        - 4.7
        - 5.1
        - 3.4
        - 3.6
        product_probabilities:
        - 0.07
        - 0.38
        - 0.06
        - 0.34
        - 0.02
        - 0.09
        - 0.01
        - 0.03
        age_on_arrival_distribution_probs:
        - 0.5
        - 0.2
        - 0.3
        fixed_order_cost: 225
        variable_order_costs:
        - 650
        - 650
        - 650
        - 650
        - 650
        - 650
        - 650
        - 650
        shortage_costs:
        - 3250
        - 3250
        - 3250
        - 3250
        - 3250
        - 3250
        - 3250
        - 3250
        wastage_costs:
        - 650
        - 650
        - 650
        - 650
        - 650
        - 650
        - 650
        - 650
        holding_costs:
        - 130
        - 130
        - 130
        - 130
        - 130
        - 130
        - 130
        - 130
        max_substitution_cost: 650
        initial_weekday: -1
        max_wastage_pc_target: 100.0
        min_service_level_pc_target: 0.0
        min_exact_match_pc_target: 0.0
        target_kpi_breach_penalty: 0.0
        max_steps_in_episode: 365
        gamma: 1.0
    replenishment:
      _target_: bloodbank_marl.policies.replenishment.heuristic.SRepPolicy
      env_name: RSPerishableIncIssueGymnax
      env_kwargs:
        n_products: 8
        max_useful_life: 3
        lead_time: 0
        max_order_quantity: 5
        max_demand: 100
      env_params:
        poisson_demand_mean:
        - 4.7
        - 4.7
        - 4.9
        - 4.7
        - 5.1
        - 3.4
        - 3.6
        product_probabilities:
        - 0.07
        - 0.38
        - 0.06
        - 0.34
        - 0.02
        - 0.09
        - 0.01
        - 0.03
        age_on_arrival_distribution_probs:
        - 0.5
        - 0.2
        - 0.3
        fixed_order_cost: 225
        variable_order_costs:
        - 650
        - 650
        - 650
        - 650
        - 650
        - 650
        - 650
        - 650
        shortage_costs:
        - 3250
        - 3250
        - 3250
        - 3250
        - 3250
        - 3250
        - 3250
        - 3250
        wastage_costs:
        - 650
        - 650
        - 650
        - 650
        - 650
        - 650
        - 650
        - 650
        holding_costs:
        - 130
        - 130
        - 130
        - 130
        - 130
        - 130
        - 130
        - 130
        max_substitution_cost: 650
        initial_weekday: -1
        max_wastage_pc_target: 100.0
        min_service_level_pc_target: 0.0
        min_exact_match_pc_target: 0.0
        target_kpi_breach_penalty: 0.0
        max_steps_in_episode: 365
        gamma: 1.0
      fixed_policy_params:
        _target_: jax.numpy.array
        object:
        - - 1
        - - 0
        - - 2
        - - 2
        - - 0
        - - 2
        - - 0
        - - 0
environment:
  desc: null
  value:
    env_name: RSPerishableIncIssueGymnax
    num_env_steps: 365
    num_warmup_days: 100
    env_params:
      poisson_demand_mean:
      - 4.7
      - 4.7
      - 4.9
      - 4.7
      - 5.1
      - 3.4
      - 3.6
      product_probabilities:
      - 0.07
      - 0.38
      - 0.06
      - 0.34
      - 0.02
      - 0.09
      - 0.01
      - 0.03
      age_on_arrival_distribution_probs:
      - 0.5
      - 0.2
      - 0.3
      fixed_order_cost: 225
      variable_order_costs:
      - 650
      - 650
      - 650
      - 650
      - 650
      - 650
      - 650
      - 650
      shortage_costs:
      - 3250
      - 3250
      - 3250
      - 3250
      - 3250
      - 3250
      - 3250
      - 3250
      wastage_costs:
      - 650
      - 650
      - 650
      - 650
      - 650
      - 650
      - 650
      - 650
      holding_costs:
      - 130
      - 130
      - 130
      - 130
      - 130
      - 130
      - 130
      - 130
      max_substitution_cost: 650
      initial_weekday: -1
      max_wastage_pc_target: 100.0
      min_service_level_pc_target: 0.0
      min_exact_match_pc_target: 0.0
      target_kpi_breach_penalty: 0.0
      max_steps_in_episode: 365
      gamma: 1.0
    env_kwargs:
      n_products: 8
      max_useful_life: 3
      lead_time: 0
      max_order_quantity: 5
      max_demand: 100
    gamma: 1.0
    types:
    - O-
    - O+
    - A-
    - A+
    - B-
    - B+
    - AB-
    - AB+
    scalar_kpis_to_log:
    - mean_total_order
    - service_level_%
    - wastage_%
    - mean_holding
    - exact_match_%
    - mean_age_at_transfusion
    - unmet_demand_units
    - expired_units
    - mean_daily_reward
    - mean_total_demand
    - mean_variable_order_cost
    - mean_fixed_order_cost
    - mean_shortage_cost
    - mean_substitution_cost
    - mean_wastage_cost
    - mean_holding_cost
    vector_kpis_to_log:
    - mean_demand_by_pt_blood_group
    - mean_order_by_product
    - service_level_%_by_pt_blood_group
    - wastage_%_by_product
    - mean_holding_by_product
    - mean_age_at_transfusion_by_pt_blood_group
    - exact_match_%_by_pt_blood_group
wandb:
  desc: null
  value:
    init:
      project: rs_eight_product_pretrain_issue
seed:
  desc: null
  value: 12
labelling_policy:
  desc: null
  value:
    _target_: bloodbank_marl.policies.issuing.heuristic.OldestCompatibleIssuingPolicy
    env_name: RSPerishableIncIssueGymnax
    env_params:
      poisson_demand_mean:
      - 4.7
      - 4.7
      - 4.9
      - 4.7
      - 5.1
      - 3.4
      - 3.6
      product_probabilities:
      - 0.07
      - 0.38
      - 0.06
      - 0.34
      - 0.02
      - 0.09
      - 0.01
      - 0.03
      age_on_arrival_distribution_probs:
      - 0.5
      - 0.2
      - 0.3
      fixed_order_cost: 225
      variable_order_costs:
      - 650
      - 650
      - 650
      - 650
      - 650
      - 650
      - 650
      - 650
      shortage_costs:
      - 3250
      - 3250
      - 3250
      - 3250
      - 3250
      - 3250
      - 3250
      - 3250
      wastage_costs:
      - 650
      - 650
      - 650
      - 650
      - 650
      - 650
      - 650
      - 650
      holding_costs:
      - 130
      - 130
      - 130
      - 130
      - 130
      - 130
      - 130
      - 130
      max_substitution_cost: 650
      initial_weekday: -1
      max_wastage_pc_target: 100.0
      min_service_level_pc_target: 0.0
      min_exact_match_pc_target: 0.0
      target_kpi_breach_penalty: 0.0
      max_steps_in_episode: 365
      gamma: 1.0
    fixed_policy_params:
      _target_: jax.numpy.array
      object:
      - - 0
        - 4
        - 2
        - -1
        - -1
        - -1
        - -1
        - -1
      - - 1
        - 0
        - 5
        - 4
        - 3
        - 2
        - -1
        - -1
      - - 2
        - 6
        - 4
        - 0
        - 3
        - 7
        - -1
        - -1
      - - 3
        - 2
        - 7
        - 6
        - 5
        - 4
        - -1
        - -1
      - - 4
        - 6
        - 2
        - 0
        - 5
        - 7
        - -1
        - -1
      - - 5
        - 4
        - 7
        - 6
        - 3
        - 2
        - -1
        - -1
      - - 6
        - 2
        - 4
        - 0
        - 7
        - 3
        - -1
        - -1
      - - 7
        - 6
        - 3
        - 2
        - 5
        - 4
        - -1
        - -1
pretraining:
  desc: null
  value:
    num_epochs: 50
    batch_size: 64
    preprocess_observations:
      _target_: bloodbank_marl.utils.pretraining.get_issue_obs
    preprocess_labels:
      _target_: bloodbank_marl.utils.pretraining.transform_issue_action_to_integer_label
    optimizer:
      _target_: optax.adam
      learning_rate: 0.005
    nn_model:
      _target_: bloodbank_marl.policies.models.flax_deterministic.IssueMultiProductPretrainMLP
      n_hidden: 64
      preprocess_observation:
        _target_: hydra.utils.get_method
        path: bloodbank_marl.utils.pretraining.passthrough
checkpoint_manager:
  desc: null
  value:
    _target_: orbax.checkpoint.CheckpointManager
    directory: checkpoints
    checkpointers:
      _target_: orbax.checkpoint.PyTreeCheckpointer
    options:
      _target_: orbax.checkpoint.CheckpointManagerOptions
      max_to_keep: 1
      create: true
evaluation:
  desc: null
  value:
    seed: 67
    eval_freq: 5
    test_evaluator:
      _target_: bloodbank_marl.utils.single_agent_fit_issue_too_fitness_manager.GymnaxFitness
      env_name: RSPerishableIncIssueGymnax
      num_env_steps: 365
      num_rollouts: 1000
      env_kwargs:
        n_products: 8
        max_useful_life: 3
        lead_time: 0
        max_order_quantity: 5
        max_demand: 100
      env_params:
        poisson_demand_mean:
        - 4.7
        - 4.7
        - 4.9
        - 4.7
        - 5.1
        - 3.4
        - 3.6
        product_probabilities:
        - 0.07
        - 0.38
        - 0.06
        - 0.34
        - 0.02
        - 0.09
        - 0.01
        - 0.03
        age_on_arrival_distribution_probs:
        - 0.5
        - 0.2
        - 0.3
        fixed_order_cost: 225
        variable_order_costs:
        - 650
        - 650
        - 650
        - 650
        - 650
        - 650
        - 650
        - 650
        shortage_costs:
        - 3250
        - 3250
        - 3250
        - 3250
        - 3250
        - 3250
        - 3250
        - 3250
        wastage_costs:
        - 650
        - 650
        - 650
        - 650
        - 650
        - 650
        - 650
        - 650
        holding_costs:
        - 130
        - 130
        - 130
        - 130
        - 130
        - 130
        - 130
        - 130
        max_substitution_cost: 650
        initial_weekday: -1
        max_wastage_pc_target: 100.0
        min_service_level_pc_target: 0.0
        min_exact_match_pc_target: 0.0
        target_kpi_breach_penalty: 0.0
        max_steps_in_episode: 365
        gamma: 1.0
      test: true
      n_devices: null
      num_warmup_days: 100
      gamma: 1.0
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714587965.932535
    t:
      1:
      - 1
      - 12
      - 45
      - 50
      - 55
      2:
      - 1
      - 12
      - 45
      - 50
      - 55
      3:
      - 16
      - 23
      4: 3.10.13
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
