# @package _global_
defaults:
  - override /policies/replenishment: order_up_to
  - override /evosax/strategy: simple_ga

wandb:
  init:
    project: de_moor_perishable_neuro_m2_exp6_fit_issue

environment:
  env_kwargs:
    max_useful_life: 2
    lead_time: 2
    max_order_quantity: 10

policies:
  optimize:
    - 1 # issuing
  replenishment:
    fixed_policy_params:
      _target_: jax.numpy.array
      object:
        - [9]