defaults:
  - environment: de_moor_perishable
  - replenishment/policy: heuristic_order_up_to
  - issuing/policy: one_product_mlp
  - _self_


wandb:
  init:
    project: "single_agent_ppo_jax_demoor"
plot_policies: True

training:
# Note steps relate the agent we are training, not both agents
  policy_to_train: 1
  num_envs: 40
  seed: 123
  lr: 2.5e-4
  num_steps: ${issuing.num_steps}
  total_timesteps: 1e5
  update_epochs: 3
  num_minibatches: 10
  gamma: 0.9
  gae_lambda: 0.95
  clip_eps: 0.2
  ent_coef: 0.01
  vf_coef: 0.5
  max_grad_norm: 0.5
  anneal_lr: True
  heuristic_params: 7 # Can leave same for issuing as not used
evaluation_seed: 456
replenishment:
  num_steps: 50
issuing:
  num_steps: 200

test_evaluator:
  _target_: bloodbank_marl.utils.gymnax_fitness.GymnaxFitness
  env_name: ${environment.env_name}
  num_env_steps: ${environment.num_env_steps}
  num_rollouts: 10000
  env_kwargs: ${environment.env_kwargs}
  env_params: ${environment.env_params}
  test: True
  n_devices:
  num_warmup_days: ${environment.num_warmup_days}
  gamma: ${environment.gamma}



