wandb_version: 1

evosax.strategy.elite_ratio:
  desc: null
  value: 0.2
evosax.strategy.sigma_decay:
  desc: null
  value: 1
evosax.strategy.sigma_init:
  desc: null
  value: 0.09691138295089818
environment:
  desc: null
  value:
    env_name: DeMoorPerishable
    num_env_steps: 1000000.0
    num_rollouts: 200
    env_kwargs:
      max_useful_life: 2
      lead_time: 1
      max_order_quantity: 10
    env_params:
      max_days_in_episode: 365
    num_warmup_days: 100
    gamma: 0.99
    kpis_log_eval:
    - mean_daily_reward
    - service_level_%
    - wastage_%
    - holding
policies:
  desc: null
  value:
    replenishment:
      _target_: bloodbank_marl.policies.replenishment.value_iteration.VIPolicy
      env_name: DeMoorPerishable
      env_kwargs:
        max_useful_life: 2
        lead_time: 1
        max_order_quantity: 10
      env_params:
        max_days_in_episode: 365
      fixed_policy_params:
        _target_: bloodbank_marl.utils.load_save_policy_params.load_vi_policy_params
        filepath: /home/ucabjmf/transfuseai/bloodbank_marl/model_cpts/de_moor_perishable/value_iteration_replenishment/m2_exp2.npy
        reshape_for_fitness: false
    issuing:
      _target_: bloodbank_marl.policies.common.FlaxMAPolicy
      model_class:
        _target_: hydra.utils.get_class
        path: bloodbank_marl.policies.models.flax_deterministic.IssueDiscreteMLP
      model_kwargs:
        n_hidden: 64
      policy_id: 1
      env_name: DeMoorPerishable
      env_kwargs:
        max_useful_life: 2
        lead_time: 1
        max_order_quantity: 10
      env_params:
        max_days_in_episode: 365
    policy_manager:
      _target_: bloodbank_marl.policies.policy_manager.PolicyManager
    pretrained:
      replenishment:
        enable: false
      issuing:
        enable: false
    optimize:
    - 1
evosax:
  desc: null
  value:
    strategy:
      _target_: bloodbank_marl.utils.evosax.strategies.simple_ga.SimpleGA
      popsize: 150
      elite_ratio: 0.2
      sigma_init: 0.09691138295089818
      sigma_decay: 1
      sigma_limit:
        _target_: operator.mul
        _args_:
        - 0.09691138295089818
        - 0.0001
    num_generations: 100
    popsize: 150
    num_train_rollouts: 100
    num_test_rollouts: 1000
    evaluate_every_k_gens: 10
    seed: 10
    fitness_shaper:
      _target_: evosax.FitnessShaper
      maximize: true
    logging:
      _target_: evosax.utils.ESLog
      num_generations: 100
      top_k: 5
      maximize: true
    checkpoint_options:
      _target_: orbax.checkpoint.CheckpointManagerOptions
      max_to_keep: 1
      create: true
wandb:
  desc: null
  value:
    init:
      project: de_moor_m2_exp2
      tags:
      - fit_issue
      - simple_ga
plot_policies:
  desc: null
  value: true
train_evaluator:
  desc: null
  value:
    _target_: bloodbank_marl.utils.gymnax_fitness.GymnaxFitness
    env_name: DeMoorPerishable
    num_env_steps: 1000000.0
    num_rollouts: 100
    env_kwargs:
      max_useful_life: 2
      lead_time: 1
      max_order_quantity: 10
    env_params:
      max_days_in_episode: 365
    test: false
    n_devices: null
    num_warmup_days: 100
    gamma: 0.99
evaluation:
  desc: null
  value:
    seed: 1337
    test_evaluator:
      _target_: bloodbank_marl.utils.gymnax_fitness.GymnaxFitness
      env_name: DeMoorPerishable
      num_env_steps: 1000000.0
      num_rollouts: 1000
      env_kwargs:
        max_useful_life: 2
        lead_time: 1
        max_order_quantity: 10
      env_params:
        max_days_in_episode: 365
      test: true
      n_devices: null
      num_warmup_days: 100
      gamma: 0.99
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.15.12
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709413791.590833
    t:
      1:
      - 12
      - 45
      - 50
      - 55
      2:
      - 12
      - 45
      - 50
      - 55
      3:
      - 15
      - 16
      - 23
      - 37
      4: 3.11.5
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
