_target_: bloodbank_marl.policies.common.FixedPolicy
policy_function:
  _target_: hydra.utils.get_method
  path: bloodbank_marl.policies.issuing.issue_priority_match
policy_params:
  _target_: jax.numpy.array
  object:
    - [0, -1, -1, -1, -1, -1, -1, -1] # O- pt
    - [1, 0, -1, -1, -1, -1, -1, -1] # O+ pt
    - [2, 0, -1, -1, -1, -1, -1, -1] # A- pt
    - [3, 2, 1, 0, -1, -1, -1, -1] # A+ pt
    - [4, 0, -1, -1, -1, -1, -1, -1] # B- pt
    - [5, 4, 1, 0, -1, -1, -1, -1] #B+ pt
    - [6, 4, 2, 0, -1, -1, -1, -1] # AB- pt
    - [7, 6, 5, 4, 3, 2, 1, 0] # AB+ pt
env_kwargs: {}