defaults:
  - environment: single_product_perishable_marl
  - policies/replenishment: value_iteration
  - policies/issuing: multi_agent_stochastic_single_product_mlp
  - _self_

plot_policies: False

wandb:
  init:
    project: "temp"
    tags:
      - "ppo"
      - "marl_env"

hydra:
  job:
    chdir: True
  searchpath:
    - pkg://bloodbank_marl.common_config

checkpoint_options:
  _target_: orbax.checkpoint.CheckpointManagerOptions
  max_to_keep: 1
  create: True

training:
# Note steps relate the agent we are training, not both agents
  seed: 123
  policy_to_train: 1
  num_envs: 200
  num_steps: ${training.issuing.num_steps} # We only train issuing with this env
  total_timesteps: 4e6
  update_epochs: 4
  num_minibatches: 10
  anneal_lr: True
  lr: 2.5e-4
  gamma: 0.99
  gae_lambda: 0.95
  clip_eps: 0.2
  ent_coef: 0.01
  vf_coef: 0.5
  max_grad_norm: 0.5 
  dual_clip: False
  dual_clip_value: 5.0 # This will only be used if dual_clip is True
  norm_adv: True
  value_clip: True
  partial_episode_bootstrapping: True

  replenishment:
    num_steps: 20
  issuing:
    num_steps: 80

evaluation:
  seed: 1337
  test_evaluator:
    _target_: bloodbank_marl.utils.marl_fitness.MarlFitness
    env_name: ${environment.env_name}
    num_env_steps: ${environment.num_env_steps}
    num_rollouts: 1000
    env_kwargs: ${environment.env_kwargs}
    env_params: ${environment.env_params}
    test: True
    n_devices:
    num_warmup_days: ${environment.num_warmup_days}
    gamma: ${environment.gamma}



