defaults:
  - environment: de_moor_perishable
  - policies/replenishment: heuristic_order_up_to
  - policies/issuing: multi_agent_stochastic_single_product_mlp
  - _self_

plot_policies: False

wandb:
  init:
    project: "single_agent_ppo_jax_demoor"

hydra:
  job:
    chdir: True
  searchpath:
    - pkg://bloodbank_marl.common_config

training:
# Note steps relate the agent we are training, not both agents
  seed: 123
  policy_to_train: 1
  num_envs: 200
  num_steps: ${training.issuing.num_steps} # We only train issuing with this env
  total_timesteps: 1e7
  update_epochs: 4
  num_minibatches: 4
  anneal_lr: True
  lr: 2.5e-4
  gamma: 0.99
  gae_lambda: 0.95
  clip_eps: 0.2
  ent_coef: 0.01
  vf_coef: 0.5
  max_grad_norm: 0.5

  replenishment:
    num_steps: 50
  issuing:
    num_steps: 200

policies:
  replenishment:
    fixed_policy_params:
      _target_: jax.numpy.array
      object:
        - [7.] # For DeMoor m=2, exp2

evaluation:
  seed: 1337
  test_evaluator:
    _target_: bloodbank_marl.utils.gymnax_fitness.GymnaxFitness
    env_name: ${environment.env_name}
    num_env_steps: ${environment.num_env_steps}
    num_rollouts: 10000
    env_kwargs: ${environment.env_kwargs}
    env_params: ${environment.env_params}
    test: True
    n_devices:
    num_warmup_days: ${environment.num_warmup_days}
    gamma: ${environment.gamma}



