# @package _global_
defaults:
  - override /environment: rs_perishable
  - override /policies/issuing: multi_agent_multi_product_mlp
  - override /policies/replenishment: heuristic_order_up_to

wandb:
  init:
    project: "temp"

train_evaluator:
  env_params:
    max_days_in_episode: 90
  num_warmup_days: 30

evosax:
  num_train_rollouts: 10
  num_test_rollouts: 50

policies:
  optimize:
    - 1 # issuing
  issuing:
    model_kwargs:
      n_hidden: [128, 128]
      preprocess_observation:
        _target_: hydra.utils.get_method
        path: bloodbank_marl.policies.models.utils.one_hot_day_of_week
  # TODO These are placeholders and should be updated
  replenishment:
    fixed_policy_params:
      _target_: jax.numpy.array
      object:
        - [1] # O-
        - [1] # O+
        - [1] # A-
        - [1] # A+
        - [1] # B-
        - [1] # B+
        - [1] # AB-
        - [1] # AB+