# @package _global_
defaults:
  - override /environment: rs_perishable
  - override /policies/issuing: multi_agent_multi_product_mlp
  - override /policies/replenishment: multi_agent_multi_product_order_up_to_mlp

wandb:
  init:
    project: "temp"

train_evaluator:
  env_params:
    max_days_in_episode: 90
  num_warmup_days: 30

evosax:
  num_train_rollouts: 10
  num_test_rollouts: 50

policies:
  optimize:
    - 0 # replenishment
    - 1 # issuing
  replenishment:
    model_kwargs:
      n_hidden: [64]
      preprocess_observation:
        _target_: hydra.utils.get_method
        path: bloodbank_marl.policies.models.utils.rep_obs_with_one_hot_day_of_week
  issuing:
    model_kwargs:
      n_hidden: [64]
      preprocess_observation:
        _target_: hydra.utils.get_method
        path: bloodbank_marl.policies.models.utils.one_hot_day_of_week