program: ../run_simopt.py
name: simopt_compare_product_probabilities
method: grid
metric:
  name: eval/return_mean
parameters:
  environment.env_params.product_probabilities:
    distribution: categorical
    values:
      - [0.1, 0.9]
      - [0.25, 0.75]
      - [0.5, 0.5]
      - [0.75, 0.25]
      - [0.9, 0.1]

  policies.issuing._target_:
    distribution: categorical
    values:
      - bloodbank_marl.policies.issuing.heuristic.ExactMatchIssuingPolicy
      - bloodbank_marl.policies.issuing.heuristic.PriorityMatchIssuingPolicy
      - bloodbank_marl.policies.issuing.heuristic.OldestCompatibleIssuingPolicy
 
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args_no_hyphens}
  - +experiment=simple_two_product_perishable/base_case_for_input_comparisons