defaults:
  - policies/replenishment: heuristic_order_up_to
  - policies/replenishment_policy_params: OEp
  - policies/issuing: heuristic_exact_match
  - environment: meneses_gymnax
  - _self_

wandb:
  init:
    project: "meneses_single_agent_eval"

hydra:
  job:
    chdir: True


evaluation:
  seed: 456
  test_evaluator:
    _target_: bloodbank_marl.utils.single_agent_gymnax_fitness.GymnaxFitness
    env_name: ${environment.env_name}
    num_env_steps: ${environment.num_env_steps}
    num_rollouts: 1000
    env_kwargs: ${environment.env_kwargs}
    env_params: ${environment.env_params}
    test: True
    n_devices:
    num_warmup_days: ${environment.num_warmup_days}
    gamma: ${environment.gamma}
