wandb_version: 1

evosax.strategy.elite_ratio:
  desc: null
  value: 0.45
evosax.strategy.sigma_decay:
  desc: null
  value: 1
evosax.strategy.sigma_init:
  desc: null
  value: 0.010860051315363436
environment:
  desc: null
  value:
    env_name: RSPerishableIncIssueGymnax
    num_env_steps: 365
    num_warmup_days: 100
    env_params:
      poisson_demand_mean:
      - 37.5
      - 37.3
      - 39.2
      - 37.8
      - 40.5
      - 27.2
      - 28.4
      product_probabilities:
      - 0.07
      - 0.38
      - 0.06
      - 0.34
      - 0.02
      - 0.09
      - 0.01
      - 0.03
      age_on_arrival_distribution_probs:
      - 0.5
      - 0.2
      - 0.3
      fixed_order_cost: 225
      variable_order_costs:
      - 650
      - 650
      - 650
      - 650
      - 650
      - 650
      - 650
      - 650
      shortage_costs:
      - 3250
      - 3250
      - 3250
      - 3250
      - 3250
      - 3250
      - 3250
      - 3250
      wastage_costs:
      - 650
      - 650
      - 650
      - 650
      - 650
      - 650
      - 650
      - 650
      holding_costs:
      - 130
      - 130
      - 130
      - 130
      - 130
      - 130
      - 130
      - 130
      max_substitution_cost: 650
      initial_weekday: -1
      max_wastage_pc_target: 100.0
      min_service_level_pc_target: 0.0
      min_exact_match_pc_target: 0.0
      target_kpi_breach_penalty: 0.0
      max_steps_in_episode: 365
      gamma: 1.0
    env_kwargs:
      n_products: 8
      max_useful_life: 3
      lead_time: 0
      max_order_quantity: 25
      max_demand: 100
    gamma: 1.0
    types:
    - O-
    - O+
    - A-
    - A+
    - B-
    - B+
    - AB-
    - AB+
    scalar_kpis_to_log:
    - mean_total_order
    - service_level_%
    - wastage_%
    - mean_holding
    - exact_match_%
    - mean_age_at_transfusion
    - unmet_demand_units
    - expired_units
    - mean_daily_reward
    - mean_total_demand
    - mean_variable_order_cost
    - mean_fixed_order_cost
    - mean_shortage_cost
    - mean_substitution_cost
    - mean_wastage_cost
    - mean_holding_cost
    vector_kpis_to_log:
    - mean_demand_by_pt_blood_group
    - mean_order_by_product
    - service_level_%_by_pt_blood_group
    - wastage_%_by_product
    - mean_holding_by_product
    - mean_age_at_transfusion_by_pt_blood_group
    - exact_match_%_by_pt_blood_group
policies:
  desc: null
  value:
    replenishment:
      _target_: bloodbank_marl.policies.replenishment.flax_nn.gymnax_deterministic.FlaxMultiProductRepPolicy
      model_class:
        _target_: hydra.utils.get_class
        path: bloodbank_marl.policies.models.flax_deterministic.RepMultiProductMLP
      model_kwargs:
        n_hidden:
        - 64
        preprocess_observation:
          _target_: hydra.utils.get_method
          path: bloodbank_marl.policies.models.utils.obs_basic
      env_name: RSPerishableIncIssueGymnax
      env_kwargs:
        n_products: 8
        max_useful_life: 3
        lead_time: 0
        max_order_quantity: 25
        max_demand: 100
      env_params:
        poisson_demand_mean:
        - 37.5
        - 37.3
        - 39.2
        - 37.8
        - 40.5
        - 27.2
        - 28.4
        product_probabilities:
        - 0.07
        - 0.38
        - 0.06
        - 0.34
        - 0.02
        - 0.09
        - 0.01
        - 0.03
        age_on_arrival_distribution_probs:
        - 0.5
        - 0.2
        - 0.3
        fixed_order_cost: 225
        variable_order_costs:
        - 650
        - 650
        - 650
        - 650
        - 650
        - 650
        - 650
        - 650
        shortage_costs:
        - 3250
        - 3250
        - 3250
        - 3250
        - 3250
        - 3250
        - 3250
        - 3250
        wastage_costs:
        - 650
        - 650
        - 650
        - 650
        - 650
        - 650
        - 650
        - 650
        holding_costs:
        - 130
        - 130
        - 130
        - 130
        - 130
        - 130
        - 130
        - 130
        max_substitution_cost: 650
        initial_weekday: -1
        max_wastage_pc_target: 100.0
        min_service_level_pc_target: 0.0
        min_exact_match_pc_target: 0.0
        target_kpi_breach_penalty: 0.0
        max_steps_in_episode: 365
        gamma: 1.0
      clip_min: -2
      clip_max: 2
      min_order_quantity: 0
    issuing:
      _target_: bloodbank_marl.policies.issuing.heuristic.PriorityMatchIssuingPolicy
      env_name: RSPerishableIncIssueGymnax
      env_params:
        poisson_demand_mean:
        - 37.5
        - 37.3
        - 39.2
        - 37.8
        - 40.5
        - 27.2
        - 28.4
        product_probabilities:
        - 0.07
        - 0.38
        - 0.06
        - 0.34
        - 0.02
        - 0.09
        - 0.01
        - 0.03
        age_on_arrival_distribution_probs:
        - 0.5
        - 0.2
        - 0.3
        fixed_order_cost: 225
        variable_order_costs:
        - 650
        - 650
        - 650
        - 650
        - 650
        - 650
        - 650
        - 650
        shortage_costs:
        - 3250
        - 3250
        - 3250
        - 3250
        - 3250
        - 3250
        - 3250
        - 3250
        wastage_costs:
        - 650
        - 650
        - 650
        - 650
        - 650
        - 650
        - 650
        - 650
        holding_costs:
        - 130
        - 130
        - 130
        - 130
        - 130
        - 130
        - 130
        - 130
        max_substitution_cost: 650
        initial_weekday: -1
        max_wastage_pc_target: 100.0
        min_service_level_pc_target: 0.0
        min_exact_match_pc_target: 0.0
        target_kpi_breach_penalty: 0.0
        max_steps_in_episode: 365
        gamma: 1.0
      fixed_policy_params:
        _target_: jax.numpy.array
        object:
        - - 0
          - 4
          - 2
          - -1
          - -1
          - -1
          - -1
          - -1
        - - 1
          - 0
          - 5
          - 4
          - 3
          - 2
          - -1
          - -1
        - - 2
          - 6
          - 4
          - 0
          - 3
          - 7
          - -1
          - -1
        - - 3
          - 2
          - 7
          - 6
          - 5
          - 4
          - -1
          - -1
        - - 4
          - 6
          - 2
          - 0
          - 5
          - 7
          - -1
          - -1
        - - 5
          - 4
          - 7
          - 6
          - 3
          - 2
          - -1
          - -1
        - - 6
          - 2
          - 4
          - 0
          - 7
          - 3
          - -1
          - -1
        - - 7
          - 6
          - 3
          - 2
          - 5
          - 4
          - -1
          - -1
    pretrained:
      replenishment:
        enable: true
        latest_checkpoint: true
        checkpoint_dir: /home/ucabjmf/transfuseai/bloodbank_marl/model_cpts/rs_eight_product_perishable/full_demand/issue_priority_match_max_sub_wastage_alt_rula/checkpoints
        checkpoint_manager:
          _target_: orbax.checkpoint.CheckpointManager
          directory: /home/ucabjmf/transfuseai/bloodbank_marl/model_cpts/rs_eight_product_perishable/full_demand/issue_priority_match_max_sub_wastage_alt_rula/checkpoints
          checkpointers:
            _target_: orbax.checkpoint.PyTreeCheckpointer
          options:
            _target_: orbax.checkpoint.CheckpointManagerOptions
            max_to_keep: 1
            create: true
      issuing:
        enable: false
    optimize:
    - 0
evosax:
  desc: null
  value:
    strategy:
      _target_: bloodbank_marl.utils.evosax.strategies.simple_ga.SimpleGA
      popsize: 150
      elite_ratio: 0.45
      sigma_init: 0.010860051315363436
      sigma_decay: 1
      sigma_limit:
        _target_: operator.mul
        _args_:
        - 0.010860051315363436
        - 0.0001
    num_generations: 100
    popsize: 150
    num_train_rollouts: 100
    num_test_rollouts: 1000
    evaluate_every_k_gens: 25
    seed: 10
    init_params_abs_max: 0
    fitness_shaper:
      _target_: evosax.FitnessShaper
      maximize: true
    logging:
      _target_: evosax.utils.ESLog
      num_generations: 100
      top_k: 5
      maximize: true
    checkpoint_options:
      _target_: orbax.checkpoint.CheckpointManagerOptions
      max_to_keep: 1
      create: true
    evo_params:
      _target_: bloodbank_marl.utils.evosax.strategies.simple_ga.EvoParams
      sigma_init: 0.010860051315363436
      sigma_limit:
        _target_: operator.mul
        _args_:
        - 0.010860051315363436
        - 0.0001
      sigma_decay: 1
      init_min:
        _target_: operator.mul
        _args_:
        - -1
        - 0
      init_max: 0
wandb:
  desc: null
  value:
    init:
      project: rs_eight_perishable_base
      tags:
      - new_type_env
      - priority_match
      - fit_rep
      - simple_ga
      - full_demand
      - rep_pretrained
plot_policy:
  desc: null
  value: false
train_evaluator:
  desc: null
  value:
    _target_: bloodbank_marl.utils.single_agent_fit_issue_too_fitness_manager.GymnaxFitness
    env_name: RSPerishableIncIssueGymnax
    num_env_steps: 90
    num_rollouts: 100
    env_kwargs:
      n_products: 8
      max_useful_life: 3
      lead_time: 0
      max_order_quantity: 25
      max_demand: 100
    env_params:
      poisson_demand_mean:
      - 37.5
      - 37.3
      - 39.2
      - 37.8
      - 40.5
      - 27.2
      - 28.4
      product_probabilities:
      - 0.07
      - 0.38
      - 0.06
      - 0.34
      - 0.02
      - 0.09
      - 0.01
      - 0.03
      age_on_arrival_distribution_probs:
      - 0.5
      - 0.2
      - 0.3
      fixed_order_cost: 225
      variable_order_costs:
      - 650
      - 650
      - 650
      - 650
      - 650
      - 650
      - 650
      - 650
      shortage_costs:
      - 3250
      - 3250
      - 3250
      - 3250
      - 3250
      - 3250
      - 3250
      - 3250
      wastage_costs:
      - 650
      - 650
      - 650
      - 650
      - 650
      - 650
      - 650
      - 650
      holding_costs:
      - 130
      - 130
      - 130
      - 130
      - 130
      - 130
      - 130
      - 130
      max_substitution_cost: 650
      initial_weekday: -1
      max_wastage_pc_target: 100.0
      min_service_level_pc_target: 0.0
      min_exact_match_pc_target: 0.0
      target_kpi_breach_penalty: 0.0
      max_steps_in_episode: 365
      gamma: 1.0
    test: false
    n_devices: null
    num_warmup_days: 25
    gamma: 1.0
evaluation:
  desc: null
  value:
    seed: 1337
    test_evaluator:
      _target_: bloodbank_marl.utils.single_agent_fit_issue_too_fitness_manager.GymnaxFitness
      env_name: RSPerishableIncIssueGymnax
      num_env_steps: 365
      num_rollouts: 1000
      env_kwargs:
        n_products: 8
        max_useful_life: 3
        lead_time: 0
        max_order_quantity: 25
        max_demand: 100
      env_params:
        poisson_demand_mean:
        - 37.5
        - 37.3
        - 39.2
        - 37.8
        - 40.5
        - 27.2
        - 28.4
        product_probabilities:
        - 0.07
        - 0.38
        - 0.06
        - 0.34
        - 0.02
        - 0.09
        - 0.01
        - 0.03
        age_on_arrival_distribution_probs:
        - 0.5
        - 0.2
        - 0.3
        fixed_order_cost: 225
        variable_order_costs:
        - 650
        - 650
        - 650
        - 650
        - 650
        - 650
        - 650
        - 650
        shortage_costs:
        - 3250
        - 3250
        - 3250
        - 3250
        - 3250
        - 3250
        - 3250
        - 3250
        wastage_costs:
        - 650
        - 650
        - 650
        - 650
        - 650
        - 650
        - 650
        - 650
        holding_costs:
        - 130
        - 130
        - 130
        - 130
        - 130
        - 130
        - 130
        - 130
        max_substitution_cost: 650
        initial_weekday: -1
        max_wastage_pc_target: 100.0
        min_service_level_pc_target: 0.0
        min_exact_match_pc_target: 0.0
        target_kpi_breach_penalty: 0.0
        max_steps_in_episode: 365
        gamma: 1.0
      test: true
      n_devices: null
      num_warmup_days: 100
      gamma: 1.0
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.15.12
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714494390.968715
    t:
      1:
      - 12
      - 45
      - 50
      - 55
      2:
      - 12
      - 45
      - 50
      - 55
      3:
      - 15
      - 16
      - 23
      - 37
      4: 3.11.5
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
