# @package _global_
defaults:
  - override /environment: rs_perishable
  - override /policies/issuing: multi_agent_multi_product_mlp
  - override /policies/replenishment: multi_agent_multi_product_order_up_to_mlp

wandb:
  init:
    project: "simple_two_perishable_base"
    tags:
      - "open_es"
      - "fit_both"
      - "marl_env"

policies:
  optimize:
    - 0 # replenishment
    - 1 # issuing
  replenishment:
    model_kwargs:
      preprocess_observation:
        _target_: hydra.utils.get_method
        path: bloodbank_marl.policies.models.utils.rep_obs