defaults:
  - policies/replenishment: heuristic_order_up_to
  - policies/replenishment_policy_params: Cp # Let's say we'll start with the current policy, BUT one parameter is outside the range
  - policies/issuing: heuristic_priority_match
  - param_search: nsgaii
  - environment: meneses_gymnax
  - _self_

wandb:
  init:
    project: "meneses_gymnax_simopt"

hydra:
  job:
    chdir: True
  searchpath:
    # Search paths assume that run_optuna_simopt.py will be run from simopt/
    - file://../conf

train_evaluator:
  _target_: bloodbank_marl.utils.single_agent_gymnax_fitness.GymnaxFitness
  env_name: ${environment.env_name}
  num_env_steps: ${environment.num_env_steps}
  num_rollouts: ${param_search.num_rollouts}
  env_kwargs: ${environment.env_kwargs}
  env_params: ${environment.env_params}
  test: False
  n_devices:
  num_warmup_days: ${environment.num_warmup_days}
  gamma: ${environment.gamma}

evaluation: 
  seed: 1337
  test_evaluator:
    _target_: bloodbank_marl.utils.single_agent_gymnax_fitness.GymnaxFitness
    env_name: ${environment.env_name}
    num_env_steps: ${environment.num_env_steps}
    num_rollouts: 10000
    env_kwargs: ${environment.env_kwargs}
    env_params: ${environment.env_params}
    test: True
    n_devices:
    num_warmup_days: ${environment.num_warmup_days}
    gamma: ${environment.gamma}
