defaults:
  - policies/replenishment: s_policy
  - policies/replenishment_policy_params: Cp # Let's say we'll start with the current policy
  - policies/issuing: priority_match
  - environment: meneses_gymnax
  - _self_

wandb:
  init:
    project: "meneses_single_agent_simopt"

hydra:
  job:
    chdir: True
  searchpath:
    # Search paths assume that run_optuna_simopt.py will be run from simopt/
    - file://../conf

rollout_wrapper:
  _target_: bloodbank_marl.utils.single_agent_rollout_manager.RolloutWrapper
  env_id: ${environment.env_name}
  num_env_steps: 365
  env_kwargs: ${environment.env_kwargs}
  env_params: ${environment.env_params}
  num_burnin_steps: 100
  return_info: False

param_search:
  sampler:
    _target_: optuna.samplers.NSGAIISampler
    population_size: 20
  max_parallel_trials: 20
  max_iterations: 200
  num_rollouts: 200
  seed: 10
  search_bounds:
    all_params:
      low: 0
      high: 100
  early_stopping_rounds: 10
 
evaluation:
  seed: 123
  num_rollouts: 1000
  rollout_wrapper:
    _target_: ${rollout_wrapper._target_}
    env_id: ${rollout_wrapper.env_id}
    num_env_steps: ${rollout_wrapper.num_env_steps}
    env_kwargs: ${rollout_wrapper.env_kwargs}
    env_params: ${rollout_wrapper.env_params}
    num_burnin_steps: 100
    return_info: True
