wandb:
  init:
    project: "ppo_demoor_single_agent"

seed: 10
n_seeds: 20
n_eval_episodes: 500

# Remember we can change these, but can't vmap over changes (probably)
fixed_config:
  NUM_ENVS: 4
  NUM_STEPS: 500
  TOTAL_TIMESTEPS: 5e5
  UPDATE_EPOCHS: 4
  NUM_MINIBATCHES: 4
  ENV_NAME: "DeMoorPerishable"
  ACTIVATION: "relu"
  ANNEAL_LR: False # Not sure about this one
  NUM_HIDDEN_UNITS: 128
  NUM_HIDDEN_LAYERS: 2


hp_config:
  LR: 5e-4
  GAMMA: 0.99
  GAE_LAMBDA: 0.95
  CLIP_EPS: 0.2
  ENT_COEF: 0.01
  VF_COEF: 0.5
  MAX_GRAD_NORM: 0.5

