_target_: bloodbank_marl.policies.common.FlaxMAPolicy
model_class:
  _target_: hydra.utils.get_class
  path: bloodbank_marl.policies.models.flax_deterministic.RepDiscreteMLP
policy_id: 0
model_kwargs:
  n_hidden: 64
env_name: ${environment.env_name}
env_kwargs: ${environment.env_kwargs}
env_params: ${environment.env_params}