defaults:
  - policies/replenishment: multi_product_stochastic_total_order_up_to_mlp
  - policies/issuing: heuristic_priority_match
  - environment: meneses_gymnax
  - _self_

plot_policy: False

wandb:
  init:
    project: "ppo_single_agent_meneses"

hydra:
  job:
    chdir: True
  searchpath:
    # Search paths assume that run_optuna_simopt.py will be run from simopt/
    - file://../conf

training:
  seed: 10
  n_seeds: 1 # This is how many repeats of training to run with different seeds

# Remember we can change these, but can't vmap over changes (probably)
fixed_config:
  num_envs: 200
  num_steps: 20
  total_timesteps: 1e7
  update_epochs: 4
  num_minibatches: 20
  anneal_lr: True
  environment: ${environment}
  policies: ${policies}

# We can vmap over different settings for these if we want
hp_config:
  lr: 1e-4
  gamma: 0.90
  gae_lambda: 0.95
  clip_eps: 0.2
  ent_coef: 0.01
  vf_coef: 0.5
  max_grad_norm: 0.5

evaluation: 
  seed: 1337
  test_evaluator:
    _target_: bloodbank_marl.utils.single_agent_gymnax_fitness.GymnaxFitness
    env_name: ${environment.env_name}
    num_env_steps: ${environment.num_env_steps}
    num_rollouts: 10000
    env_kwargs: ${environment.env_kwargs}
    env_params: ${environment.env_params}
    test: True
    n_devices:
    num_warmup_days: ${environment.num_warmup_days}
    gamma: ${environment.gamma}
