_target_: bloodbank_marl.policies.issuing.heuristic.OldestCompatibleIssuingPolicy
env_name: ${environment.env_name}
#env_kwargs: ${environment.env_kwargs}
env_params: ${environment.env_params}
fixed_policy_params:
  _target_: jax.numpy.array
  object:
    - [0, -1, -1, -1, -1, -1, -1, -1] # O- pt
    - [1, 0, -1, -1, -1, -1, -1, -1] # O+ pt
    - [2, 0, -1, -1, -1, -1, -1, -1] # A- pt
    - [3, 2, 1, 0, -1, -1, -1, -1] # A+ pt
    - [4, 0, -1, -1, -1, -1, -1, -1] # B- pt
    - [5, 4, 1, 0, -1, -1, -1, -1] #B+ pt
    - [6, 4, 2, 0, -1, -1, -1, -1] # AB- pt
    - [7, 6, 5, 4, 3, 2, 1, 0] # AB+ pt