_target_: bloodbank_marl.policies.replenishment.flax_nn.gymnax_deterministic.FlaxMultiProductCategoricalOrderUpToRepPolicy
model_class:
  _target_: hydra.utils.get_class
  path: bloodbank_marl.policies.models.flax_deterministic.RepMultiProductCategoricalMLP
model_kwargs:
  n_hidden: 64
env_name: ${environment.env_name}
env_kwargs: ${environment.env_kwargs}
env_params: ${environment.env_params}