defaults:
  - heuristic_policies/replenishment: heuristic_order_up_to
  - heuristic_policies/issuing: heuristic_oufo
  - policies/replenishment: multi_agent_single_product_mlp
  - policies/issuing: multi_agent_single_product_mlp
  - param_search: grid
  - environment: de_moor_perishable
  - _self_

wandb:
  init:
    project: "de_moor_pareto_frontier_plots"

hydra:
  job:
    chdir: True
  searchpath:
    - pkg://bloodbank_marl.common_config

evaluation: 
  seed: 10191
  record_overall_metrics_per_eval_rollout: True
  test_evaluator:
    _target_: bloodbank_marl.utils.marl_fitness.MarlFitness
    env_name: ${environment.env_name}
    num_env_steps: ${environment.num_env_steps}
    num_rollouts: 10000
    env_kwargs: ${environment.env_kwargs}
    env_params: ${environment.env_params}
    test: True
    n_devices:
    num_warmup_days: ${environment.num_warmup_days}
    gamma: ${environment.gamma}

policies:
  policy_manager:
    _target_: bloodbank_marl.policies.policy_manager.PolicyManager
  pretrained:
    replenishment:
      enable: False
    issuing:
      enable: False