wandb_version: 1

training.issuing.clip_eps:
  desc: null
  value: 0.397066903052636
training.issuing.ent_coef:
  desc: null
  value: 0.0007023389243059356
training.issuing.gae_lambda:
  desc: null
  value: 0.8625586883652179
training.issuing.gamma:
  desc: null
  value: 0.9223998491328992
training.issuing.lr:
  desc: null
  value: 0.008088663189282433
training.issuing.max_grad_norm:
  desc: null
  value: 0.8962843328926734
training.issuing.update_epochs:
  desc: null
  value: 2
training.issuing.vf_coef:
  desc: null
  value: 0.878285423428355
training.replenishment.clip_eps:
  desc: null
  value: 0.13194366732878066
training.replenishment.ent_coef:
  desc: null
  value: 0.0001172071222885741
training.replenishment.gae_lambda:
  desc: null
  value: 0.9806494288906206
training.replenishment.gamma:
  desc: null
  value: 0.978674729211795
training.replenishment.lr:
  desc: null
  value: 0.0012871463931509377
training.replenishment.max_grad_norm:
  desc: null
  value: 0.3243113885406235
training.replenishment.update_epochs:
  desc: null
  value: 4
training.replenishment.vf_coef:
  desc: null
  value: 0.17040019619073654
environment:
  desc: null
  value:
    env_name: DeMoorPerishable
    num_env_steps: 1000000.0
    num_rollouts: 200
    env_kwargs:
      max_useful_life: 5
      lead_time: 1
      max_order_quantity: 10
    env_params:
      max_demand: 100
      demand_gamma_mean: 4.0
      demand_gamma_cov: 0.5
      variable_order_cost: 3.0
      shortage_cost: 5.0
      wastage_cost: 7.0
      holding_cost: 1.0
      max_days_in_episode: 365
    num_warmup_days: 100
    gamma: 0.99
    kpis_log_eval:
    - mean_daily_reward
    - service_level_%
    - wastage_%
    - holding
policies:
  desc: null
  value:
    replenishment:
      _target_: bloodbank_marl.policies.replenishment.flax_nn.marl_stochastic.FlaxStochasticOrderUpToRepPolicy
      model_class:
        _target_: hydra.utils.get_class
        path: bloodbank_marl.policies.models.flax_stochastic.DiscreteActorCritic
      model_kwargs:
        n_hidden: 64
      policy_id: 0
      env_name: DeMoorPerishable
      env_kwargs:
        max_useful_life: 5
        lead_time: 1
        max_order_quantity: 10
      env_params:
        max_demand: 100
        demand_gamma_mean: 4.0
        demand_gamma_cov: 0.5
        variable_order_cost: 3.0
        shortage_cost: 5.0
        wastage_cost: 7.0
        holding_cost: 1.0
        max_days_in_episode: 365
    issuing:
      _target_: bloodbank_marl.policies.common.FlaxStochasticMAPolicy
      model_class:
        _target_: hydra.utils.get_class
        path: bloodbank_marl.policies.models.flax_stochastic.DiscreteActorCritic
      model_kwargs:
        n_hidden: 64
      policy_id: 1
      env_name: DeMoorPerishable
      env_kwargs:
        max_useful_life: 5
        lead_time: 1
        max_order_quantity: 10
      env_params:
        max_demand: 100
        demand_gamma_mean: 4.0
        demand_gamma_cov: 0.5
        variable_order_cost: 3.0
        shortage_cost: 5.0
        wastage_cost: 7.0
        holding_cost: 1.0
        max_days_in_episode: 365
plot_policies:
  desc: null
  value: false
wandb:
  desc: null
  value:
    init:
      project: de_moor_m5_exp2
      tags:
      - ppo
      - fit_both
      - marl_env
checkpoint_options:
  desc: null
  value:
    _target_: orbax.checkpoint.CheckpointManagerOptions
    max_to_keep: 1
    create: true
training:
  desc: null
  value:
    num_envs: 200
    seed: 123
    replenishment:
      num_envs: 200
      lr: 0.0012871463931509377
      num_steps: 20
      total_timesteps: 1000000.0
      update_epochs: 4
      num_minibatches: 10
      gamma: 0.978674729211795
      gae_lambda: 0.9806494288906206
      clip_eps: 0.13194366732878066
      ent_coef: 0.0001172071222885741
      vf_coef: 0.17040019619073654
      max_grad_norm: 0.3243113885406235
      anneal_lr: true
      dual_clip: false
      dual_clip_value: 5.0
      norm_adv: true
      value_clip: true
      partial_episode_bootstrapping: true
    issuing:
      num_envs: 200
      lr: 0.008088663189282433
      num_steps: 80
      total_timesteps: 4000000.0
      update_epochs: 2
      num_minibatches: 40
      gamma: 0.9223998491328992
      gae_lambda: 0.8625586883652179
      clip_eps: 0.397066903052636
      ent_coef: 0.0007023389243059356
      vf_coef: 0.878285423428355
      max_grad_norm: 0.8962843328926734
      anneal_lr: true
      dual_clip: false
      dual_clip_value: 5.0
      norm_adv: true
      value_clip: true
      partial_episode_bootstrapping: true
evaluation:
  desc: null
  value:
    seed: 1337
    test_evaluator:
      _target_: bloodbank_marl.utils.gymnax_fitness.GymnaxFitness
      env_name: DeMoorPerishable
      num_env_steps: 1000000.0
      num_rollouts: 1000
      env_kwargs:
        max_useful_life: 5
        lead_time: 1
        max_order_quantity: 10
      env_params:
        max_demand: 100
        demand_gamma_mean: 4.0
        demand_gamma_cov: 0.5
        variable_order_cost: 3.0
        shortage_cost: 5.0
        wastage_cost: 7.0
        holding_cost: 1.0
        max_days_in_episode: 365
      test: true
      n_devices: null
      num_warmup_days: 100
      gamma: 0.99
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.15.12
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1710366825.994123
    t:
      1:
      - 12
      - 45
      - 50
      - 55
      2:
      - 12
      - 45
      - 50
      - 55
      3:
      - 15
      - 16
      - 23
      - 37
      4: 3.11.5
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
