sampler:
  _target_: optuna.samplers.GridSampler
max_parallel_trials: 50
max_iterations: 100
num_rollouts: 4000
seed: 10
search_bounds:
  all_params:
    low: 0
    high: ${environment.env_kwargs.max_order_quantity}