wandb_version: 1

evosax.strategy.elite_ratio:
  desc: null
  value: 0.35000000000000003
evosax.strategy.sigma_decay:
  desc: null
  value: 0.999
evosax.strategy.sigma_init:
  desc: null
  value: 0.015275730312699904
policies:
  desc: null
  value:
    replenishment:
      _target_: bloodbank_marl.policies.replenishment.flax_nn.gymnax_deterministic.FlaxOrderUpToRepPolicy
      model_class:
        _target_: hydra.utils.get_class
        path: bloodbank_marl.policies.models.flax_deterministic.RepDiscreteMLP
      model_kwargs:
        n_hidden: 64
      env_name: DeMoorPerishableGymnax
      env_kwargs:
        max_useful_life: 2
        lead_time: 2
        max_order_quantity: 10
        issuing_policy: fifo
      env_params: {}
    pretrained:
      enable: false
evosax:
  desc: null
  value:
    strategy:
      _target_: bloodbank_marl.utils.evosax.strategies.simple_ga.SimpleGA
      popsize: 150
      elite_ratio: 0.35000000000000003
      sigma_init: 0.015275730312699904
      sigma_decay: 0.999
      sigma_limit:
        _target_: operator.mul
        _args_:
        - 0.015275730312699904
        - 0.0001
    num_generations: 100
    popsize: 150
    num_train_rollouts: 100
    num_test_rollouts: 1000
    evaluate_every_k_gens: 10
    seed: 10
    fitness_shaper:
      _target_: evosax.FitnessShaper
      maximize: true
    logging:
      _target_: evosax.utils.ESLog
      num_generations: 100
      top_k: 5
      maximize: true
    checkpoint_options:
      _target_: orbax.checkpoint.CheckpointManagerOptions
      max_to_keep: 1
      create: true
environment:
  desc: null
  value:
    env_name: DeMoorPerishableGymnax
    num_env_steps: 365
    num_warmup_days: 100
    env_params: {}
    env_kwargs:
      max_useful_life: 2
      lead_time: 2
      max_order_quantity: 10
      issuing_policy: fifo
    gamma: 0.99
    types: []
    scalar_kpis_to_log:
    - mean_daily_reward
    - service_level_%
    - wastage_%
    - mean_holding
    vector_kpis_to_log: null
plot_policy:
  desc: null
  value: false
wandb:
  desc: null
  value:
    init:
      project: de_moor_m2_exp6
      tags:
      - fit_rep
      - simple_ga
train_evaluator:
  desc: null
  value:
    _target_: bloodbank_marl.utils.single_agent_gymnax_fitness.GymnaxFitness
    env_name: DeMoorPerishableGymnax
    num_env_steps: 365
    num_rollouts: 100
    env_kwargs:
      max_useful_life: 2
      lead_time: 2
      max_order_quantity: 10
      issuing_policy: fifo
    env_params: {}
    test: false
    n_devices: null
    num_warmup_days: 100
    gamma: 0.99
evaluation:
  desc: null
  value:
    seed: 1337
    test_evaluator:
      _target_: bloodbank_marl.utils.single_agent_gymnax_fitness.GymnaxFitness
      env_name: DeMoorPerishableGymnax
      num_env_steps: 365
      num_rollouts: 1000
      env_kwargs:
        max_useful_life: 2
        lead_time: 2
        max_order_quantity: 10
        issuing_policy: fifo
      env_params: {}
      test: true
      n_devices: null
      num_warmup_days: 100
      gamma: 0.99
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.15.12
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709246400.459761
    t:
      1:
      - 12
      - 45
      - 50
      - 55
      2:
      - 12
      - 45
      - 50
      - 55
      3:
      - 15
      - 16
      - 23
      - 37
      4: 3.11.5
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
