# @package _global_

defaults:
  - override /environment: rs_perishable
  - override /policies/replenishment: multi_product_order_up_to_mlp
  - override /policies/issuing: exact_match

wandb:
  init:
    project: rs_marl_neuroevo_test

environment:
  env_params:
    age_on_arrival_distribution_probs: 
      _target_: jax.numpy.array
      object: [0.5, 0.2, 0.3]

