_target_: bloodbank_marl.policies.replenishment.FlaxOrderUpToRepPolicy
model_class:
  _target_: hydra.utils.get_class
  path: bloodbank_marl.policies.replenishment.RepDiscreteMLP
model_kwargs:
  n_hidden: 64
policy_id: 0
env_name: ${environment.env_name}
env_kwargs: ${environment.env_kwargs}
env_params: ${environment.env_params}