_target_: bloodbank_marl.policies.common.FixedPolicy
policy_function:
  _target_: hydra.utils.get_method
  path: bloodbank_marl.policies.replenishment.order_up_to
policy_params: 10
env_kwargs: ${environment.env_kwargs}