_target_: bloodbank_marl.policies.replenishment.flax_nn.gymnax_stochastic.FlaxStochasticMultiProductOrderUpToRepPolicy
model_class:
    _target_: hydra.utils.get_class
    path: bloodbank_marl.policies.models.flax_stochastic.ContinuousActorCritic
model_kwargs:
    activation: "tanh"
    preprocess_observation:
        _target_: hydra.utils.get_method
        path: bloodbank_marl.policies.models.utils.total_stock_on_hand_and_in_transit_by_product
env_name: ${environment.env_name}
env_kwargs: ${environment.env_kwargs}
env_params: ${environment.env_params}