_target_: bloodbank_marl.policies.replenishment.heuristic.SRepPolicy
env_name: ${environment.env_name}
env_kwargs: ${environment.env_kwargs}
env_params: ${environment.env_params}
fixed_policy_params:
