defaults:
  - environment: de_moor_perishable
  - policies/replenishment: discrete_order_up_to_mlp
  - policies/issuing: discrete_mlp
  - _self_

wandb:
  init:
    project: "bloodbank_marl_neuroevolution_default"

evaluation:
  seed: 1234
  test_evaluator:
    _target_: bloodbank_marl.utils.gymnax_fitness.GymnaxFitness
    env_name: ${environment.env_name}
    num_env_steps: ${environment.num_env_steps}
    num_rollouts: 10000
    env_kwargs: ${environment.env_kwargs}
    env_params: ${environment.env_params}
    test: True
    n_devices:
    num_warmup_days: ${environment.num_warmup_days}
    gamma: ${environment.gamma}