defaults:
  - environment: de_moor_perishable
  - policies/replenishment: multi_agent_single_product_order_up_to_mlp
  - policies/issuing: multi_agent_single_product_mlp
  - policies/load_replenishment_policy_params: flax_nn
  - policies/load_issuing_policy_params: flax_nn
  - _self_

wandb:
  init:
    project: "bloodbank_marl_evaluation_default"
    tags:
      - "evaluation"
      - "marl_env"

hydra:
  job:
    chdir: True
  searchpath:
    - pkg://bloodbank_marl.common_config

policies:
  policy_manager:
    _target_: bloodbank_marl.policies.policy_manager.PolicyManager

evaluation:
  seed: 24601
  record_overall_metrics_per_eval_rollout: True
  test_evaluator:
    _target_: bloodbank_marl.utils.marl_fitness.MarlFitness
    env_name: ${environment.env_name}
    num_env_steps: ${environment.num_env_steps}
    num_rollouts: 10000
    env_kwargs: ${environment.env_kwargs}
    env_params: ${environment.env_params}
    test: True
    n_devices:
    num_warmup_days: ${environment.num_warmup_days}
    gamma: ${environment.gamma}